### ISSUE TITLE
I don't understand the output order

### ISSUE THREAD

**Issue by nilesjohnson** [timhutton/twitter-archive-parser#8] opened 2022-11-10 15:23 UTC
The output from my data appears to be mixed up.  (The html file from twitter is ordered by date, as expected.)  My output starts with some tweets from 2015, then 2014, 2013, then 2016, 2018, 2022, 2018 again, 2016 again, back to 2018, then 2019, 2018, 2019, 2016, 2017, 2020, etc.  It appears to be a mix of tweets, retweets, and replies.  Maybe the json import just jumbles them up? (my python version is 3.10.6).

I can't discern any pattern, nor did I see any error in the script output.  I spot-checked for some specific tweets, and didn't see any missing.  Skimming through, I don't see any obvious parsing errors.  Also, I'm not worried enough about it to investigate further.  I'm just very happy to have the content there, and I can find what I need easily enough!!! Thanks! :)

p.s. Maybe one other detail in case it's useful: I downloaded my twitter archive April 29, 2022, so maybe there was some minor change in format between then and now?  I wouldn't worry about it, and especially not if there are no other reports of a problem like this.

p.p.s. Oh, checking my `tweet.js` file, the output from your script appears to be in the same order as the entries there.  (At least, the first few and last few are the same.)  So the twitter html file must include some feature to sort by date.  I guess I'll post this issue anyway, just in case it comes up for others.

**Comment by timhutton** [comment] 2022-11-10 15:38
Thanks Niles. Agreed. I'd just a few moments ago captured this issue. Duplicate of #7.

**Closed** 2022-11-10 15:39 UTC

**Comment by timhutton** [comment] 2022-11-10 15:45
(OK, I don't know how to mark as issue as a duplicate of another. I'm sure that used to work.)
